services:
  - type: web
    name: kosmicheskiy-klikker
    env: node
    region: frankfurt # или другой регион по вашему выбору
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        generateValue: true
      - key: TELEGRAM_BOT_TOKEN
        sync: false
    healthCheckPath: /api/health
    numInstances: 1
    plan: free # бесплатный тариф